### ISSUE TITLE
OF 0.9.3 osx: 'gst/gst.h' file not found

### ISSUE THREAD

**Issue by giovannibedetti** [arturoc/ofxGStreamer#16]
I am trying to compile the example project with OF 0.9.3 on osx 10.9.5 with Xcode 6.2
The project for Xcode has been generated with the projectGenerator.
Gstreamer packages have been installed following the instructions.
I get:
/of_v0.9.3_osx_release/libs/openFrameworks/video/ofGstUtils.h:12:10: 'gst/gst.h' file not found

**Comment by arturoc** [comment]
this is fix now in OF master and should be fixed in the nightly builds from today on

**Comment by ntzovanis** [comment]
@arturoc I'm using OF 0.9.8 in osx (Xcode 8) and I'm having the same issue. Is it possible to fix 0.9.8 to be able to compile without using the nightly builds?

Thanks!

**Comment by rvegele** [comment]
same in 0.10.1

**Comment by arturoc** [comment]
what platform?

**Comment by ImanolGo** [comment]
MacOS Sierra

**Comment by icq4ever** [comment]
there's a error in header search path setting in xCode.
add path manually, then this error resolved. 
<img width="804" alt="image" src="https://user-images.githubusercontent.com/530796/61594842-3be5d500-ac2b-11e9-8e84-2b89b54d3598.png">

**Comment by arturoc** [comment]
@icq4ever does it work if you add that path to addon_config.mk in the osx section?
