### ISSUE TITLE
Does not compile OF 0.9.8

### ISSUE THREAD

**Issue by steeley** [arturoc/ofxGStreamer#18]
Followed your install instructions **exactly**. Using of0.9.8 OS X 10.11.6  shows the following errors occur  when trying to compile the example, the files are there and even if you add the files manually there is still the error :

/Volumes/Extra/of_v0.9.8_osx_release/libs/openFrameworks/video/ofGstUtils.h:12:10: 'gst/gst.h' file not found
No such file or directory: '/libs/openFrameworks/video/ofGstVideoPlayer.cpp'
No such file or directory: '/libs/openFrameworks/video/ofGstUtils.cpp'
No such file or directory: '/libs/openFrameworks/video/ofGstVideoGrabber.cpp'
No input files

**Comment by arturoc** [comment]
yes this addon won't work with 0.9.8's project generator, you need to use the latest version from the nighly builds. you can even use the project generator from the nightly builds with 0.9.8

**Comment by steeley** [comment]
thanks - did try this but could not build project generator so got nowhere with gStreamer.

I will use FFMpeg instead as this works for me.

**Comment by arturoc** [comment]
you don't need to build the project generator, just download the latest nightly build from the OF web and put it the OF folder

**Comment by steeley** [comment]
Do you have a link? I can't find the nightly build download.
