### ISSUE TITLE
Different behavior between ofVideoPlayer with or without gstreamer

### ISSUE THREAD

**Issue by dimitre** [arturoc/ofxGStreamer#27]
on ofVideoPlayer when I pause video the isPlaying() boolean returns false, so I can toggle play/pause with the following command:
```c++
	if (key == ' ') {
		v->setPaused(v->isPlaying());
	}
```
using gstreamer it returns true even when paused.

**Comment by arturoc** [comment]
if i remember correctly the correct flag is `isPaused` is playing returns true whenever the video is not stopped even if it's paused. whoever implemented the latest apis in windows or macos might have got this wrong. can you open an issue in the core regarding this? the implementation for gstreamer is there too anyway
